### ISSUE TITLE
Huiswerkopdracht 3

### ISSUE THREAD

**Issue by maartenpaauw** [m44rt3np44uw/IPMEDT3J#2]
<b>Maarten Paauw</b> heeft een kaart <a href="http://ift.tt/2hhFubg">Huiswerkopdracht 3</a> aan de lijst <b>TODO</b> toegevoegd om December 7, 2016 at 12:09PM<br><br><br><br><a href="http://ift.tt/2hhFubg">Bekijk op Trello</a>

**Comment by Luquatic** [comment]
Huiswerkopdracht 3 is voltooid
